# generic
"image_dimension": 128
"device": "cpu"  # cpu or cuda
"augmentations" : {
  "rotation_augmentations": 50,  # +/- in degrees
  "translation_augmentations": 0,  # % translation of image before resizing
  "image_flips" : True
}

# for CNN
"cnn_config" : {
  "model_configuraton": "VGG19_512_32_1",
  "batch_size": 10,
  "epocs": 10,
  "learning_rate": { # a single number will use the Adam optimizer, a list will use SGD as a schedule
    "epocs": [ 3,6,9 ],
    "rates": [ 0.001,0.0003,0.00001 ]
  }
}


