# generic
"image_dimention": 128
"device": "cpu"  # cpu or cuda
"rotation_augmentations": 50  # +/- in degrees
"translation_augmentations": 0  # % translation of image before resizing

# for CNN
"model_configuraton": "VGG19_512_32_1"
"batchsize": 10
"epocs" : 10
"learning_rate" : {
                    "epocs" : [3,6,9],
                    "rates" : [0.001,0.0003,0.00001]
}
#"learning_rate" : 0.001 # a single number will use the Adam optimizer, a list will use SGD as a schedule

