# see configuration.py for documentation

# generic
"image_dimension": 384
"image_shaping" : "resize"
"device": "cuda"  # cpu or cuda

# for image augmentation
"augmentations" : {
  "rotation_augmentations": 30,  # +/- in degrees
  "translation_augmentations": [0,0],  # % translation of image before resizing
  "image_flips" : True
}

# for CNN
"cnn_config" : {
  "model_configuraton": "resnetv2_101x1_bitm",
  "batch_size": 16,
  "epocs": 10,
  "learning_rate": { # a single number will use the Adam optimizer, a list will use SGD as a schedule
    "epocs": [ 3,6,9 ],
    "rates": [ 0.001,0.0003,0.00001 ]
  }
}

# for regression
"regression_config" : {
  "features_to_use" : ['Subject Focus', 'Eyes', 'Face', 'Near', 'Action', 'Accessory',
                       'Group', 'Collage', 'Human', 'Occlusion', 'Info', 'Blur','black', 'white',
                       'pixel_width', 'dominant_red', 'dominant_green', 'dominant_blue',
                       'avg_red', 'avg_green', 'avg_blue', 'bluriness_score',
                       'scale_0_alpha', 'scale_0_std',
                       'scale_0_shift_1_mean',
                       'scale_0_shift_2_mean',
                       'scale_0_shift_3_mean',
                       'scale_0_shift_4_mean','scale_1_alpha', 'scale_1_std',
                       'scale_1_shift_1_mean',
                       'scale_1_shift_2_mean',
                       'scale_1_shift_3_mean',
                       'scale_1_shift_4_mean',
                       'brisque', 'tv'],
  "regression_mode" : "dense_nn"
}
