"model_configuraton": "VGG19_512_32_1"
"image_dimention": 128
"batchsize": 10
"rotation_augmentations": 50  # +/- in degrees
"translation_augmentations": 0  # % translation of image before resizing
"device": "cpu"  # cpu or cuda
"epocs" : 10,
"learning_rate" : 0.001 # a single number will use the Adam optimizer, a list will use SGD as a schedule

