version: "3.9"
services:
  kapet:
    build:
      context: scratch
      target: kapet
    image: kapet
    ports:
      - 8888:8888
    volumes:
      - ./lib:/home/kapet/lib
      - ./input:/home/kapet/input
    entrypoint: "jupyter lab --ip 0.0.0.0 --no-browser --allow-root --gpus all"  # start jupyter lab
  kapet_gpu:
    build:
      context: scratch
      target: kapet_gpu
    runtime: nvidia
    image: kapet
    ports:
    - 8888:8888
    volumes:
      - ./lib:/home/kapet/lib
      - ./input:/home/kapet/input
    entrypoint: "jupyter lab --ip 0.0.0.0 --no-browser --allow-root --gpus all"  # start jupyter lab
  #kapet_gpu:
  #  build: .
  #  image: kapet_gpu
  #  ports:
  #  - 8888:8888
  #  volumes:
  #    - ./lib:/home/kapet/lib
  #    - ./input:/home/kapet/input
  #  deploy: # requires docker-compose v1.28+
  #    resources:
  #      reservations:
  #        devices:
  #          - driver: nvidia
  #            count: all
  #            capabilities: [gpu]
  #  entrypoint: "jupyter lab --ip 0.0.0.0 --no-browser --allow-root"  # start jupyter lab
