version: "3.9"
services:
  kapet:
    build: .
    image: kapet
    ports:
    - 8888:8888
    volumes:
      - ./lib:/home/kapet/lib
      - ./input:/home/kapet/input
    entrypoint: "jupyter lab --ip 0.0.0.0 --no-browser --allow-root"  # start jupyter lab

