version: "3.9"
services:
  kapet:
    build:
      context: .
      target: kapet
    image: kapet
    ports:
      - 8888:8888
    volumes:
      - ./lib:/home/kapet/lib
      - ./input:/home/kapet/input
      - ./notebooks:/home/kapet/notebooks
    entrypoint: "jupyter lab --ip 0.0.0.0 --no-browser --allow-root"  # start jupyter lab

  kapet_gpu:
    build:
      context: .
      target: kapet_gpu
    runtime: nvidia
    image: kapet
    ports:
    - 8888:8888
    volumes:
      - ./lib:/home/kapet/lib
      - ./input:/home/kapet/input
      - ./notebooks:/home/kapet/notebooks
      - ./experiments:/home/kapet/experiments
    entrypoint: "jupyter lab --ip 0.0.0.0 --no-browser --allow-root"  # start jupyter lab

